
INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Camile Lopes','01829543728');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Adriele Beatriz','90952329050');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Deborah Regina','09914774651');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Maicon Gerardi','11224567891');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Matheus Camilo','17843717773');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Guilherme Silveira','99127518256');


INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,1,'1','998765436','WHATSAPP');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,1,'1','998762000','CELULAR');

INSERT INTO CONTATO_CLIENTE 
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,2,'2','978574231','WHATSAPP');

INSERT INTO CONTATO_CLIENTE 
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,2,'2','900654839','TELEGRAM');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,3,'1','963784765','WHATSAPP');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,3,'2','941347960','CELULAR');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,4,'2','923895764','CELULAR');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,4,'2','910945949','WHATS');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,5,'1','939593879','CELULAR');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,5,'1','939592000','TELEGRAM');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,6,'2','985863813','TELEFONE FIXO');

INSERT INTO CONTATO_CLIENTE
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_CLIENTE.NEXTVAL,6,'1','809592000','TELEGRAM');


INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,1,'RUA ARMINDO CRUZ',33,'MARAPONGA','64987-090',1);

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,2,'AV. DESEMBARGADOR MOREIRA',53,'CENTRO','67845-870',1);

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,3,'RUA JULIO CESAR',78,'BOCA DO RIO','41984-780',1);

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,4,'AV. OSWALDO ARANHA',153,'CENTRO','40845-200',1);

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,5,'RUA DOUTOR FLORES',178,'CIDADE BAIXA','57984-18',2);

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP,TIPO)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,6,'24 DE OUTUBRO',178,'AUXILIADORA','90460-200',2);



INSERT INTO FUNCIONARIO 
(ID_FUNCIONARIO,NOME,CARGO,SALARIO)
VALUES (SEQ_FUNCIONARIO.NEXTVAL,'Janaína','ATENDENTE',1200.00);

INSERT INTO FUNCIONARIO 
(ID_FUNCIONARIO,NOME,CARGO,SALARIO)
VALUES (SEQ_FUNCIONARIO.NEXTVAL,'Roberto','MOTOBOY',1000.00);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,1);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,2);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,3);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,1);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,4);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,5);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,5);

INSERT INTO PEDIDO
(ID_PEDIDO,ID_CLIENTE)
VALUES (SEQ_PEDIDO.NEXTVAL,6);

INSERT INTO PRODUTO 
(ID_PRODUTO, TIPO_PRODUTO, NOME, PRECO)
VALUES (SEQ_PRODUTO.NEXTVAL,'2','COCA COLA 1 LITRO',5.00);

INSERT INTO PRODUTO 
(ID_PRODUTO,TIPO_PRODUTO, NOME, PRECO)
VALUES (SEQ_PRODUTO.NEXTVAL,'2','GUARANA 1 LITRO',4.50);

INSERT INTO PRODUTO 
(ID_PRODUTO, TIPO_PRODUTO, NOME, PRECO)
VALUES (SEQ_PRODUTO.NEXTVAL,'1','PIZZA CALABRESA',20.00);

INSERT INTO PRODUTO 
(ID_PRODUTO, TIPO_PRODUTO, NOME, PRECO)
VALUES (SEQ_PRODUTO.NEXTVAL,'1','PIZZA FRANGO COM CATUPIRY',30.00);

INSERT INTO PRODUTO 
(ID_PRODUTO, TIPO_PRODUTO, NOME, PRECO)
VALUES (SEQ_PRODUTO.NEXTVAL,'1','PIZZA PORTUGUESA',30.00);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (1,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (1,2,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (1,3,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (2,2,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (2,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (3,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (4,4,2);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (4,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (5,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (5,3,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (6,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (6,3,2);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (7,2,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (7,1,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (8,2,1);

INSERT INTO PEDIDO_PRODUTO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE)
VALUES (8,1,1);