---TABELA CLIENTES

CREATE TABLE VEM_SER.CLIENTE (
ID_CLIENTE INT NOT NULL,
NOME VARCHAR2(255) NOT NULL,
CPF VARCHAR2(11) UNIQUE NOT NULL,
PRIMARY KEY (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT * FROM CLIENTE c 
INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Camile Lopes','01829543728');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Adriele Beatriz','90952329050');

INSERT INTO CLIENTE 
(ID_CLIENTE,NOME,CPF)
VALUES (SEQ_CLIENTE.NEXTVAL,'Debora Maria','71541605004');

--- TABELA CONTATOS

CREATE TABLE CONTATO_RESTAURANTE(
ID_CONTATO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
TIPO VARCHAR2(20) NOT NULL,
NUMERO VARCHAR2(9) NOT NULL,
DESCRICAO VARCHAR2(255),
PRIMARY KEY(ID_CONTATO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_CONTATO_RESTAURANTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CONTATO_RESTAURANTE 
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_RESTAURANTE.NEXTVAL,1,'RESIDENCIAL','998765436','WHATS');

INSERT INTO CONTATO_RESTAURANTE 
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_RESTAURANTE.NEXTVAL,2,'COMERCIAL','987654839','WHATS');

INSERT INTO CONTATO_RESTAURANTE 
(ID_CONTATO,ID_CLIENTE,TIPO,NUMERO,DESCRICAO)
VALUES (SEQ_CONTATO_RESTAURANTE.NEXTVAL,3,'RESIDENCIAL','963784765','WHATS');

-------- TABELA ENDEREÇOS

CREATE TABLE ENDERECO_CLIENTE(
ID_ENDERECO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO NUMBER NOT NULL,
BAIRRO VARCHAR2(255) NOT NULL,
CEP VARCHAR2(9) NOT NULL,
PRIMARY KEY (ID_ENDERECO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_ENDERECO_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,1,'RUA ARMINDO CRUZ',33,'MARAPONGA','64987-09');

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,2,'AV. DESEMBARGADOR MOREIRA',53,'CENTRO','67845-87');

INSERT INTO ENDERECO_CLIENTE 
(ID_ENDERECO,ID_CLIENTE,LOGRADOURO,NUMERO,BAIRRO,CEP)
VALUES(SEQ_ENDERECO_CLIENTE.NEXTVAL,3,'RUA JULIO CESAR',78,'BOCA DO RIO','41984-78');

-----TABELA FUNCIONARIOS

CREATE TABLE VEM_SER.FUNCIONARIO (
ID_FUNCIONARIO INT NOT NULL,
CARGO VARCHAR2 (255) NOT NULL,
SALARIO DECIMAL(5,2) NOT NULL,
PRIMARY KEY (id_FUNCIONARIO)
);

UPDATE FUNCIONARIO 
SET TIPO = DECIMAL(6,2)
WHERE TIPO = DECIMAL(5,2)

ALTER TABLE FUNCIONARIO 
MODIFY SALARIO DECIMAL(6,2);


CREATE SEQUENCE SEQ_FUNCIONARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



INSERT INTO FUNCIONARIO 
(ID_FUNCIONARIO,CARGO,SALARIO)
VALUES (SEQ_FUNCIONARIO.NEXTVAL,'ATENDENTE',200.00)

INSERT INTO FUNCIONARIO 
(ID_FUNCIONARIO,CARGO,SALARIO)
VALUES (SEQ_FUNCIONARIO.NEXTVAL,'MOTOBOY',1000.00)


UPDATE FUNCIONARIO 
SET SALARIO = 1200.00
WHERE SALARIO = 200.00

SELECT * FROM FUNCIONARIO f 


------TABELA PEDIDOS

CREATE
TABLE VEM_SER.PEDIDO (
ID_PEDIDO INT NOT NULL,
ID_CLIENTE INT  NOT NULL,
PRIMARY KEY (ID_PEDIDO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


----TABELA PRODUTOS

CREATE
TABLE VEM_SER.PRODUTO (
ID_PRODUTO INT NOT NULL,
NOME VARCHAR2(255) NOT NULL,
TIPO VARCHAR2(255) NOT NULL,
PRECO DECIMAL(5,2) NOT NULL,
PRIMARY KEY (ID_PRODUTO)
);

CREATE SEQUENCE SEQ_PRODUTO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

------TABELA PEDIDO _ PRODUTOS
CREATE
TABLE VEM_SER.PEDIDO_PRODUTO (
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT  NOT NULL,
PRIMARY KEY (ID_PEDIDO,ID_PRODUTO),
 CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
 CONSTRAINT FK_PRODUTO_PEDIDO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO) 
);










